// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_ota_control                     23
#define gattdb_steps                           26
#define gattdb_pressure                        29
#define gattdb_accel_z_axis                    32
#define gattdb_accel_y_axis                    35
#define gattdb_accel_x_axis                    38
#define gattdb_temperature_measurement         41
#define gattdb_elevation                       44
#define gattdb_altitude                        47

#endif
